### ISSUE TITLE
a small bug

### ISSUE THREAD

**Issue by MichaelWayneLIU** [GoSecure/php7-opcache-override#5] opened 2017-11-28 11:13 UTC
Zend Bin ID should be like this zend_bin_id = "BIN_" + bin_id_suffix

```
# Zend Bin ID suffix
if architecture == "x86_64":
    bin_id_suffix = "148888"
else:
    bin_id_suffix = "144444"

zend_bin_id = "BIN_" + bin_id_suffix
```

**Comment by obilodeau** [comment] 2017-11-28 17:54
Can you attach an opcache file that fails to decompile so we can reproduce?

**Comment by MichaelWayneLIU** [comment] 2017-11-29 01:46
I tried to use system_id_scraper.py to  extract the system_id of a phpinfo() page.However,I get a system_id that does not match the directory name generated by my SUSE Linux Enterprise Server.So I changed the Zend Bin ID,get the right one~

**Comment by obilodeau** [comment] 2017-11-29 03:40
This probably changed in a recent release of PHP or is customized by the distributor.

Can you provide us with:
* your exact PHP version
* Zend Extension Build
* Architecture
* Real system_id (from opcache directory)

We will probably have to adapt the code starting from a specific version otherwise opcache parsing of older versions will not work.

Thanks!

**Comment by MichaelWayneLIU** [comment] 2017-12-04 02:16
Sure,

- PHP Version 7.0.6

- Zend Extension ID : API320151012,NTS

- Zend Bin ID : BIN_148888

- x86_64 architecture

- real System ID : 54da662ee9a5cb7999a9112b88c1b244

**Comment by xr1s** [comment] 2018-03-31 17:25
Same issue.
* PHP Version: 7.2.4
* Zend Extension ID: API320170718,NTS
* Zend Bin ID: BIN_148888
* x86_64 architecture
* generated System ID: bf8cb777af4c2311e75a70c7f2a29983
* real System ID: 4524545105632f9bc156e358f564530c

**Comment by CyrusF** [comment] 2018-04-01 06:55
Regarding **[Zend Bin ID]** as **[BIN_SIZEOF_CHAR4\*\*\*\*]** form can generate the real System ID

- PHP version : 7.0.28-0ubuntu0.16.04.1
- Zend Extension ID : API320151012,NTS
- Zend Bin ID : BIN_SIZEOF_CHAR48888
- Assuming x86_64 architecture
- generated System ID : 135d7b6d92600479c439863a7df8f815
- read System ID: 135d7b6d92600479c439863a7df8f815

**Comment by petk** [comment] 2019-03-14 22:40
Hello, I was just browsing GitHub and landed here. The BIN_SIZEOF_CHAR48888 is/was done because there was an undefined macro in the:
https://github.com/php/php-src/blob/bb75a537719c3b749548e4a4d133a7b5b778b468/ext/opcache/ZendAccelerator.c#L2565

so it's more of a typo for versions up to PHP 7.3.x.

With PHP 7.4.x it will be now changed to a more proper looking `BIN_48888` for 64bit architectures... SIZEOF_CHAR is always 1.

https://github.com/php/php-src/pull/3947

Redacted: Instead of previously picked `BIN_148888` the id will be `BIN_48888`...

**Comment by obilodeau** [comment] 2019-03-20 03:59
Thanks everyone for your patience.

Here's what has been done:
- if php < 7.4: output two different System IDs, one with the `BIN_SIZEOF_CHAR` mistake and one without.  Two attempts is a lot less work than bruteforce :wink: 
- if php > 7.4: use `BIN_48888` for 64-bit and `BIN_44444` for 32-bit

Fix is in master

**Closed as completed by obilodeau** 2019-03-20 03:59 UTC
